[package]
name = "bitwarden-ipc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[features]
wasm = ["dep:tsify-next", "dep:wasm-bindgen"] # WASM support

[dependencies]
bitwarden-core = { workspace = true, features = ["internal"] }
tsify-next = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[lints]
workspace = true
