name: Rust tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-pass:
    name: Check if tests passed
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - name: Check if tests passed
        run: exit 0

  test:
    name: ${{ matrix.os }} / default
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macOS-14
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check Rustup
        run: rustup component add llvm-tools

      - name: Check Rustup
        run: rustup --version

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Test
        run: cargo test --workspace --all-features
